"""add column in challenges

Revision ID: 168a3f31cace
Revises: 1093835a1051
Create Date: 2020-09-24 17:43:24.169283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168a3f31cace'
down_revision = '1093835a1051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('grade', sa.Enum('beginner', 'middle'), nullable=True))
    op.add_column('challenges', sa.Column('to_read', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'to_read')
    op.drop_column('challenges', 'grade')
    # ### end Alembic commands ###
